# Generated by Django 6.0.5 on 2026-06-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('point', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
