# Generated by Django 6.0.5 on 2026-06-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ชื่อสินค้า')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียดสินค้า')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปสินค้า')),
                ('other', models.CharField(blank=True, null=True, verbose_name='อื่นๆ')),
            ],
        ),
    ]
